export const layoutTags = [
  { tagName: "div", id: -1, attributes: {}, styles: {}, children: [] },
  { tagName: "p", id: -2, attributes: {}, styles: {}, children: [] },
  { tagName: "span", id: -3, attributes: {}, styles: {}, children: [] },
  { tagName: "h1", id: -4, attributes: {}, styles: {}, children: [] },
  { tagName: "h2", id: -5, attributes: {}, styles: {}, children: [] },
  { tagName: "h3", id: -6, attributes: {}, styles: {}, children: [] },
  { tagName: "h4", id: -7, attributes: {}, styles: {}, children: [] },
  { tagName: "h5", id: -8, attributes: {}, styles: {}, children: [] },
  { tagName: "h6", id: -9, attributes: {}, styles: {}, children: [] },
  { tagName: "ul", id: -12, attributes: {}, styles: {}, children: [] },
  { tagName: "li", id: -13, attributes: {}, styles: {}, children: [] },
  { tagName: "ol", id: -14, attributes: {}, styles: {}, children: [] },
  { tagName: "table", id: -15, attributes: {}, styles: {}, children: [] },
  { tagName: "thead", id: -16, attributes: {}, styles: {}, children: [] },
  { tagName: "tbody", id: -17, attributes: {}, styles: {}, children: [] },
  { tagName: "tr", id: -18, attributes: {}, styles: {}, children: [] },
  { tagName: "th", id: -19, attributes: {}, styles: {}, children: [] },
  { tagName: "td", id: -20, attributes: {}, styles: {}, children: [] },
  { tagName: "nav", id: -28, attributes: {}, styles: {}, children: [] },
  { tagName: "section", id: -29, attributes: {}, styles: {}, children: [] },
  { tagName: "article", id: -30, attributes: {}, styles: {}, children: [] },
  { tagName: "aside", id: -31, attributes: {}, styles: {}, children: [] },
  { tagName: "footer", id: -32, attributes: {}, styles: {}, children: [] },
  { tagName: "header", id: -33, attributes: {}, styles: {}, children: [] },
  { tagName: "main", id: -34, attributes: {}, styles: {}, children: [] },
  { tagName: "blockquote", id: -38, attributes: {}, styles: {}, children: [] },
  { tagName: "pre", id: -39, attributes: {}, styles: {}, children: [] },
  { tagName: "code", id: -40, attributes: {}, styles: {}, children: [] },
  { tagName: "hr", id: -41, attributes: {}, styles: {}, children: [] },
  { tagName: "br", id: -42, attributes: {}, styles: {}, children: [] },
  { tagName: "strong", id: -43, attributes: {}, styles: {}, children: [] },
  { tagName: "em", id: -44, attributes: {}, styles: {}, children: [] },
  { tagName: "b", id: -45, attributes: {}, styles: {}, children: [] },
  { tagName: "i", id: -46, attributes: {}, styles: {}, children: [] },
  { tagName: "small", id: -47, attributes: {}, styles: {}, children: [] },
  { tagName: "sup", id: -48, attributes: {}, styles: {}, children: [] },
  { tagName: "sub", id: -49, attributes: {}, styles: {}, children: [] },
  { tagName: "dl", id: -50, attributes: {}, styles: {}, children: [] },
  { tagName: "dt", id: -51, attributes: {}, styles: {}, children: [] },
  { tagName: "dd", id: -52, attributes: {}, styles: {}, children: [] },
];

export const controllerTags = [
  {
    tagName: "a",
    id: -10,
    attributes: { href: "#" },
    styles: {},
    children: [],
  },
  {
    tagName: "img",
    id: -11,
    attributes: { src: "", alt: "" },
    styles: {},
    children: [],
  },
  {
    tagName: "button",
    id: -21,
    attributes: { type: "button" },
    styles: {},
    children: [],
  },
  {
    tagName: "input",
    id: -22,
    attributes: { type: "text" },
    styles: {},
    children: [],
  },
  { tagName: "textarea", id: -23, attributes: {}, styles: {}, children: [] },
  { tagName: "form", id: -24, attributes: {}, styles: {}, children: [] },
  { tagName: "label", id: -25, attributes: {}, styles: {}, children: [] },
  { tagName: "select", id: -26, attributes: {}, styles: {}, children: [] },
  { tagName: "option", id: -27, attributes: {}, styles: {}, children: [] },
  {
    tagName: "video",
    id: -35,
    attributes: { controls: true, src: "" },
    styles: {},
    children: [],
  },
  {
    tagName: "audio",
    id: -36,
    attributes: { controls: true, src: "" },
    styles: {},
    children: [],
  },
  {
    tagName: "iframe",
    id: -37,
    attributes: { src: "" },
    styles: {},
    children: [],
  },
];
