const countries = [
  { country: "Andorra", code: "AD", languages: ["Catalan"] },
  { country: "United Arab Emirates", code: "AE", languages: ["Arabic"] },
  { country: "Afghanistan", code: "AF", languages: ["Pashto", "Dari"] },
  { country: "Antigua and Barbuda", code: "AG", languages: ["English"] },
  { country: "Anguilla", code: "AI", languages: ["English"] },
  { country: "", code: "AH", languages: [] },
  { country: "", code: "AK", languages: [] },
  { country: "Albania", code: "AL", languages: ["Albanian"] },
  { country: "Armenia", code: "AM", languages: ["Armenian"] },
  {
    country: "Netherlands Antilles",
    code: "AN",
    languages: ["Dutch", "Papiamento"],
  },
  { country: "Angola", code: "AO", languages: ["Portuguese"] },
  { country: "Antarctica", code: "AQ", languages: [] },
  { country: "Argentina", code: "AR", languages: ["Spanish"] },
  { country: "American Samoa", code: "AS", languages: ["English", "Samoan"] },
  { country: "Austria", code: "AT", languages: ["German"] },
  { country: "Australia", code: "AU", languages: ["English"] },
  { country: "Aruba", code: "AW", languages: ["Dutch", "Papiamento"] },
  { country: "Åland Islands", code: "AX", languages: ["Swedish"] },
  { country: "Azerbaijan", code: "AZ", languages: ["Azerbaijani"] },
  {
    country: "Bosnia and Herzegovina",
    code: "BA",
    languages: ["Bosnian", "Croatian", "Serbian"],
  },
  { country: "Barbados", code: "BB", languages: ["English"] },
  { country: "Bangladesh", code: "BD", languages: ["Bengali"] },
  { country: "Belgium", code: "BE", languages: ["Dutch", "French", "German"] },
  { country: "Burkina Faso", code: "BF", languages: ["French"] },
  { country: "Bulgaria", code: "BG", languages: ["Bulgarian"] },
  { country: "Bahrain", code: "BH", languages: ["Arabic"] },
  {
    country: "Burundi",
    code: "BI",
    languages: ["Kirundi", "French", "English"],
  },
  { country: "Benin", code: "BJ", languages: ["French"] },
  { country: "Saint Barthélemy", code: "BL", languages: ["French"] },
  { country: "Bermuda", code: "BM", languages: ["English"] },
  { country: "Brunei Darussalam", code: "BN", languages: ["Malay"] },
  {
    country: "Bolivia",
    code: "BO",
    languages: ["Spanish", "Quechua", "Aymara"],
  },
  {
    country: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
    languages: ["Dutch", "Papiamento"],
  },
  { country: "Brazil", code: "BR", languages: ["Portuguese"] },
  { country: "Bahamas", code: "BS", languages: ["English"] },
  { country: "Bhutan", code: "BT", languages: ["Dzongkha"] },
  { country: "Bouvet Island", code: "BV", languages: [] },
  { country: "Botswana", code: "BW", languages: ["English", "Setswana"] },
  { country: "Belarus", code: "BY", languages: ["Belarusian", "Russian"] },
  { country: "Belize", code: "BZ", languages: ["English"] },
  { country: "Canada", code: "CA", languages: ["English", "French"] },
  { country: "Cocos (Keeling) Islands", code: "CC", languages: ["English"] },
  {
    country: "Congo, The Democratic Republic Of The",
    code: "CD",
    languages: ["French", "Lingala", "Kikongo", "Swahili", "Tshiluba"],
  },
  {
    country: "Central African Republic",
    code: "CF",
    languages: ["French", "Sango"],
  },
  { country: "Congo", code: "CG", languages: ["French"] },
  {
    country: "Switzerland",
    code: "CH",
    languages: ["German", "French", "Italian", "Romansh"],
  },
  { country: "Côte D'Ivoire", code: "CI", languages: ["French"] },
  {
    country: "Cook Islands",
    code: "CK",
    languages: ["English", "Cook Islands Maori"],
  },
  { country: "Chile", code: "CL", languages: ["Spanish"] },
  { country: "Cameroon", code: "CM", languages: ["French", "English"] },
  { country: "China", code: "CN", languages: ["Chinese"] },
  { country: "Colombia", code: "CO", languages: ["Spanish"] },
  { country: "Costa Rica", code: "CR", languages: ["Spanish"] },
  { country: "Cuba", code: "CU", languages: ["Spanish"] },
  { country: "Cape Verde", code: "CV", languages: ["Portuguese"] },
  { country: "Curaçao", code: "CW", languages: ["Dutch", "Papiamento"] },
  { country: "Christmas Island", code: "CX", languages: ["English"] },
  { country: "Cyprus", code: "CY", languages: ["Greek", "Turkish"] },
  { country: "Czech Republic", code: "CZ", languages: ["Czech"] },
  { country: "Germany", code: "DE", languages: ["German"] },
  { country: "Djibouti", code: "DJ", languages: ["French", "Arabic"] },
  { country: "Denmark", code: "DK", languages: ["Danish"] },
  { country: "Dominica", code: "DM", languages: ["English"] },
  { country: "Dominican Republic", code: "DO", languages: ["Spanish"] },
  { country: "Algeria", code: "DZ", languages: ["Arabic", "Berber"] },
  { country: "Ecuador", code: "EC", languages: ["Spanish"] },
  { country: "Estonia", code: "EE", languages: ["Estonian"] },
  { country: "Egypt", code: "EG", languages: ["Arabic"] },
  { country: "Western Sahara", code: "EH", languages: ["Arabic", "Spanish"] },
  {
    country: "Eritrea",
    code: "ER",
    languages: ["Tigrinya", "Arabic", "English"],
  },
  { country: "Spain", code: "ES", languages: ["Spanish"] },
  { country: "Ethiopia", code: "ET", languages: ["Amharic"] },
  { country: "Finland", code: "FI", languages: ["Finnish", "Swedish"] },
  { country: "Fiji", code: "FJ", languages: ["Fijian", "Hindi", "English"] },
  {
    country: "Falkland Islands (Malvinas)",
    code: "FK",
    languages: ["English"],
  },
  {
    country: "Micronesia, Federated States Of",
    code: "FM",
    languages: ["English"],
  },
  { country: "Faroe Islands", code: "FO", languages: ["Faroese", "Danish"] },
  { country: "France", code: "FR", languages: ["French"] },
  { country: "Gabon", code: "GA", languages: ["French"] },
  { country: "United Kingdom", code: "GB", languages: ["English"] },
  { country: "Grenada", code: "GD", languages: ["English"] },
  { country: "Georgia", code: "GE", languages: ["Georgian"] },
  { country: "French Guiana", code: "GF", languages: ["French"] },
  { country: "Guernsey", code: "GG", languages: ["English"] },
  { country: "Ghana", code: "GH", languages: ["English"] },
  { country: "Gibraltar", code: "GI", languages: ["English"] },
  { country: "Greenland", code: "GL", languages: ["Danish"] },
  { country: "Gambia", code: "GM", languages: ["English"] },
  { country: "Guinea", code: "GN", languages: ["French"] },
  { country: "Guadeloupe", code: "GP", languages: ["French"] },
  {
    country: "Equatorial Guinea",
    code: "GQ",
    languages: ["Spanish", "French", "Portuguese"],
  },
  { country: "Greece", code: "GR", languages: ["Greek"] },
  {
    country: "South Georgia and the South Sandwich Islands",
    code: "GS",
    languages: ["English"],
  },
  { country: "Guatemala", code: "GT", languages: ["Spanish"] },
  { country: "Guam", code: "GU", languages: ["English", "Chamorro"] },
  { country: "Guinea-Bissau", code: "GW", languages: ["Portuguese"] },
  { country: "Guyana", code: "GY", languages: ["English"] },
  { country: "Hong Kong", code: "HK", languages: ["Chinese", "English"] },
  { country: "Heard and McDonald Islands", code: "HM", languages: [] }, // No official languages
  { country: "Honduras", code: "HN", languages: ["Spanish"] },
  { country: "Croatia", code: "HR", languages: ["Croatian"] },
  { country: "Haiti", code: "HT", languages: ["Haitian Creole", "French"] },
  { country: "Hungary", code: "HU", languages: ["Hungarian"] },
  { country: "Iceland", code: "IS", languages: ["Icelandic"] },
  { country: "Indonesia", code: "ID", languages: ["Indonesian"] },
  { country: "Ireland", code: "IE", languages: ["Irish", "English"] },
  { country: "Israel", code: "IL", languages: ["Hebrew", "Arabic"] },
  { country: "Isle of Man", code: "IM", languages: ["English"] },
  {
    country: "India",
    code: "IN",
    languages: ["Hindi", "English", "22 other officially recognized languages"],
  },
  {
    country: "British Indian Ocean Territory",
    code: "IO",
    languages: ["English"],
  },
  { country: "Iraq", code: "IQ", languages: ["Arabic", "Kurdish"] },
  { country: "Iran, Islamic Republic Of", code: "IR", languages: ["Persian"] },
  { country: "Italy", code: "IT", languages: ["Italian"] },
  { country: "Jersey", code: "JE", languages: ["English"] },
  { country: "Jamaica", code: "JM", languages: ["English"] },
  { country: "Jordan", code: "JO", languages: ["Arabic"] },
  { country: "Japan", code: "JP", languages: ["Japanese"] },
  { country: "Kenya", code: "KE", languages: ["Swahili", "English"] },
  { country: "Kyrgyzstan", code: "KG", languages: ["Kyrgyz", "Russian"] },
  { country: "Cambodia", code: "KH", languages: ["Khmer"] },
  { country: "Kiribati", code: "KI", languages: ["Gilbertese", "English"] },
  {
    country: "Comoros",
    code: "KM",
    languages: ["Comorian", "Arabic", "French"],
  },
  { country: "Saint Kitts And Nevis", code: "KN", languages: ["English"] },
  {
    country: "Korea, Democratic People's Republic Of",
    code: "KP",
    languages: ["Korean"],
  },
  { country: "Korea, Republic of", code: "KR", languages: ["Korean"] },
  { country: "Kuwait", code: "KW", languages: ["Arabic"] },
  { country: "Cayman Islands", code: "KY", languages: ["English"] },
  { country: "Kazakhstan", code: "KZ", languages: ["Kazakh", "Russian"] },
  {
    country: "Lao People's Democratic Republic",
    code: "LA",
    languages: ["Lao"],
  },
  { country: "Lebanon", code: "LB", languages: ["Arabic"] },
  { country: "Saint Lucia", code: "LC", languages: ["English"] },
  { country: "Liechtenstein", code: "LI", languages: ["German"] },
  { country: "Sri Lanka", code: "LK", languages: ["Sinhala", "Tamil"] },
  { country: "Liberia", code: "LR", languages: ["English"] },
  { country: "Lesotho", code: "LS", languages: ["Sesotho", "English"] },
  { country: "Lithuania", code: "LT", languages: ["Lithuanian"] },
  {
    country: "Luxembourg",
    code: "LU",
    languages: ["Luxembourgish", "French", "German"],
  },
  { country: "Latvia", code: "LV", languages: ["Latvian"] },
  { country: "Libya", code: "LY", languages: ["Arabic"] },
  { country: "Morocco", code: "MA", languages: ["Arabic", "Berber"] },
  { country: "Monaco", code: "MC", languages: ["French"] },
  { country: "Moldova, Republic of", code: "MD", languages: ["Romanian"] },
  { country: "Montenegro", code: "ME", languages: ["Montenegrin"] },
  { country: "Saint Martin", code: "MF", languages: ["French"] },
  { country: "Madagascar", code: "MG", languages: ["Malagasy", "French"] },
  {
    country: "Marshall Islands",
    code: "MH",
    languages: ["Marshallese", "English"],
  },
  {
    country: "Macedonia, the Former Yugoslav Republic Of",
    code: "MK",
    languages: ["Macedonian"],
  },
  {
    code: "ML",
    name: "Mali",
    languages: ["French"],
  },
  {
    code: "MM",
    name: "Myanmar",
    languages: ["Burmese"],
  },
  {
    code: "MN",
    name: "Mongolia",
    languages: ["Mongolian"],
  },
  {
    code: "MO",
    name: "Macao",
    languages: ["Chinese (Cantonese)", "Portuguese"],
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    languages: ["English", "Chamorro", "Carolinian"],
  },
  {
    code: "MQ",
    name: "Martinique",
    languages: ["French"],
  },
  {
    code: "MR",
    name: "Mauritania",
    languages: ["Arabic"],
  },
  {
    code: "MS",
    name: "Montserrat",
    languages: ["English"],
  },
  {
    code: "MT",
    name: "Malta",
    languages: ["Maltese", "English"],
  },
  {
    code: "MU",
    name: "Mauritius",
    languages: ["English", "French"],
  },
  {
    code: "MV",
    name: "Maldives",
    languages: ["Dhivehi"],
  },
  {
    code: "MW",
    name: "Malawi",
    languages: ["Chichewa", "English"],
  },
  {
    code: "MX",
    name: "Mexico",
    languages: ["Spanish"],
  },
  {
    code: "MY",
    name: "Malaysia",
    languages: ["Malay"],
  },
  {
    code: "MZ",
    name: "Mozambique",
    languages: ["Portuguese"],
  },
  {
    code: "NA",
    name: "Namibia",
    languages: ["English", "Afrikaans", "Oshiwambo"],
  },
  {
    code: "NC",
    name: "New Caledonia",
    languages: ["French"],
  },
  {
    code: "NE",
    name: "Niger",
    languages: ["French"],
  },
  {
    code: "NF",
    name: "Norfolk Island",
    languages: ["English", "Norfolk"],
  },
  {
    code: "NG",
    name: "Nigeria",
    languages: ["English", "Hausa", "Yoruba", "Igbo"],
  },
  {
    code: "NI",
    name: "Nicaragua",
    languages: ["Spanish"],
  },
  {
    code: "NL",
    name: "Netherlands",
    languages: ["Dutch"],
  },
  {
    code: "NO",
    name: "Norway",
    languages: ["Norwegian"],
  },
  {
    code: "NP",
    name: "Nepal",
    languages: ["Nepali"],
  },
  {
    code: "NR",
    name: "Nauru",
    languages: ["Nauruan", "English"],
  },
  {
    code: "NU",
    name: "Niue",
    languages: ["Niuean", "English"],
  },
  {
    code: "NY",
    name: "New York",
    languages: [],
  },
  {
    code: "NZ",
    name: "New Zealand",
    languages: ["English", "Māori"],
  },
  {
    code: "OM",
    name: "Oman",
    languages: ["Arabic"],
  },
  {
    code: "PA",
    name: "Panama",
    languages: ["Spanish"],
  },
  {
    code: "PE",
    name: "Peru",
    languages: ["Spanish", "Quechua", "Aymara"],
  },
  {
    code: "PF",
    name: "French Polynesia",
    languages: ["French"],
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    languages: ["Tok Pisin", "Hiri Motu", "English"],
  },
  {
    code: "PH",
    name: "Philippines",
    languages: ["Filipino", "English"],
  },
  {
    code: "PK",
    name: "Pakistan",
    languages: ["Urdu", "English"],
  },
  {
    code: "PL",
    name: "Poland",
    languages: ["Polish"],
  },
  {
    code: "PM",
    name: "Saint Pierre And Miquelon",
    languages: ["French"],
  },
  {
    code: "PN",
    name: "Pitcairn",
    languages: ["English"],
  },
  {
    code: "PR",
    name: "Puerto Rico",
    languages: ["Spanish", "English"],
  },
  {
    code: "PS",
    name: "Palestine, State of",
    languages: ["Arabic"],
  },
  {
    code: "PT",
    name: "Portugal",
    languages: ["Portuguese"],
  },
  {
    code: "PW",
    name: "Palau",
    languages: ["Palauan", "English"],
  },
  {
    code: "PY",
    name: "Paraguay",
    languages: ["Spanish", "Guarani"],
  },
  {
    code: "QA",
    name: "Qatar",
    languages: ["Arabic"],
  },
  {
    code: "RE",
    name: "Réunion",
    languages: ["French"],
  },
  {
    code: "RO",
    name: "Romania",
    languages: ["Romanian"],
  },
  {
    code: "RS",
    name: "Serbia",
    languages: ["Serbian"],
  },
  {
    code: "RU",
    name: "Russian Federation",
    languages: ["Russian"],
  },
  {
    code: "RW",
    name: "Rwanda",
    languages: ["Kinyarwanda", "French", "English"],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    languages: ["Arabic"],
  },
  {
    code: "SB",
    name: "Solomon Islands",
    languages: ["English", "Solomon Islands Pijin"],
  },
  {
    code: "SC",
    name: "Seychelles",
    languages: ["French", "English", "Seychellois Creole"],
  },
  {
    code: "SD",
    name: "Sudan",
    languages: ["Arabic", "English"],
  },
  {
    code: "SE",
    name: "Sweden",
    languages: ["Swedish"],
  },
  {
    code: "SG",
    name: "Singapore",
    languages: ["English", "Mandarin", "Malay", "Tamil"],
  },
  {
    code: "SH",
    name: "Saint Helena",
    languages: ["English"],
  },
  {
    code: "SI",
    name: "Slovenia",
    languages: ["Slovene"],
  },
  {
    code: "SJ",
    name: "Svalbard And Jan Mayen",
    languages: ["Norwegian"],
  },
  {
    code: "SK",
    name: "Slovakia",
    languages: ["Slovak"],
  },
  {
    code: "SL",
    name: "Sierra Leone",
    languages: ["English", "Krio"],
  },
  {
    code: "SM",
    name: "San Marino",
    languages: ["Italian"],
  },
  {
    code: "SN",
    name: "Senegal",
    languages: ["French"],
  },
  {
    code: "SO",
    name: "Somalia",
    languages: ["Somali", "Arabic"],
  },
  {
    code: "SR",
    name: "Suriname",
    languages: ["Dutch"],
  },
  {
    code: "SS",
    name: "South Sudan",
    languages: ["English"],
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    languages: ["Portuguese"],
  },
  {
    code: "SV",
    name: "El Salvador",
    languages: ["Spanish"],
  },
  {
    code: "SX",
    name: "Sint Maarten",
    languages: ["Dutch", "English"],
  },
  {
    code: "SY",
    name: "Syrian Arab Republic",
    languages: ["Arabic"],
  },
  {
    code: "SZ",
    name: "Swaziland",
    languages: ["Swazi", "English"],
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    languages: ["English"],
  },
  {
    code: "TD",
    name: "Chad",
    languages: ["French", "Arabic"],
  },
  {
    code: "TF",
    name: "French Southern Territories",
    languages: ["French"],
  },
  {
    code: "TG",
    name: "Togo",
    languages: ["French"],
  },
  {
    code: "TH",
    name: "Thailand",
    languages: ["Thai"],
  },
  {
    code: "TJ",
    name: "Tajikistan",
    languages: ["Tajik"],
  },
  {
    code: "TK",
    name: "Tokelau",
    languages: ["Tokelauan", "English"],
  },
  {
    code: "TL",
    name: "Timor-Leste",
    languages: ["Tetum", "Portuguese"],
  },
  {
    code: "TM",
    name: "Turkmenistan",
    languages: ["Turkmen"],
  },
  {
    code: "TN",
    name: "Tunisia",
    languages: ["Arabic"],
  },
  {
    code: "TO",
    name: "Tonga",
    languages: ["Tongan", "English"],
  },
  {
    code: "TR",
    name: "Turkey",
    languages: ["Turkish"],
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    languages: ["English"],
  },
  {
    code: "TV",
    name: "Tuvalu",
    languages: ["Tuvaluan", "English"],
  },
  {
    code: "TW",
    name: "Taiwan, Republic Of China",
    languages: ["Mandarin", "Taiwanese Hokkien", "Hakka"],
  },
  {
    code: "TZ",
    name: "Tanzania, United Republic of",
    languages: ["Swahili", "English"],
  },
  {
    code: "UA",
    name: "Ukraine",
    languages: ["Ukrainian"],
  },
  {
    code: "UG",
    name: "Uganda",
    languages: ["English", "Swahili"],
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    languages: ["English"],
  },
  {
    code: "US",
    name: "United States",
    languages: ["English"],
  },
  {
    code: "UY",
    name: "Uruguay",
    languages: ["Spanish"],
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    languages: ["Uzbek"],
  },
  {
    code: "VA",
    name: "Holy See (Vatican City State)",
    languages: ["Latin", "Italian"],
  },
  {
    code: "VC",
    name: "Saint Vincent And The Grenadines",
    languages: ["English"],
  },
  {
    code: "VE",
    name: "Venezuela, Bolivarian Republic of",
    languages: ["Spanish"],
  },
  {
    code: "VG",
    name: "Virgin Islands, British",
    languages: ["English"],
  },
  {
    code: "VI",
    name: "Virgin Islands, U.S.",
    languages: ["English"],
  },
  {
    code: "VN",
    name: "Vietnam",
    languages: ["Vietnamese"],
  },
  {
    code: "VU",
    name: "Vanuatu",
    languages: ["Bislama", "English", "French"],
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    languages: ["French"],
  },
  {
    code: "WS",
    name: "Samoa",
    languages: ["Samoan", "English"],
  },
  {
    code: "XK",
    name: "Kosovo",
    languages: ["Albanian", "Serbian"],
  },
  {
    code: "YE",
    name: "Yemen",
    languages: ["Arabic"],
  },
  {
    code: "YT",
    name: "Mayotte",
    languages: ["French"],
  },
  {
    code: "ZA",
    name: "South Africa",
    languages: [
      "Afrikaans",
      "English",
      "isiNdebele",
      "isiXhosa",
      "isiZulu",
      "Sesotho",
      "Setswana",
      "siSwati",
      "Sepedi",
    ],
  },
  {
    code: "ZM",
    name: "Zambia",
    languages: [
      "English",
      "Bemba",
      "Nyanja",
      "Tonga",
      "Lozi",
      "Silozi",
      "Kaonde",
      "Lunda",
      "Luvale",
      "Chewa",
    ],
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    languages: ["English", "Shona", "Sindebele"],
  },
];
